# Playbook to call multiple roles to configure systems
- name: Configure systems
  hosts: all
  become: yes

  tasks:

 - name: Update apt-get repo and cache
   apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

- name: Call Roles
  hosts: all
  roles:
   #- hostname
   #- firewalld
   #- ntp-config
   - motd
